# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pm_app.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pm_app.proto',
  package='pm_app',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cpm_app.proto\x12\x06pm_app\"\x1a\n\x0c\x41ssetDetails\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\tDataPoint\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"\x11\n\x0fResultDataPoint\"\x1a\n\x07Success\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2o\n\x05PMApp\x12\x36\n\x07GetData\x12\x14.pm_app.AssetDetails\x1a\x11.pm_app.DataPoint\"\x00\x30\x01\x12.\n\x08SendData\x12\x11.pm_app.DataPoint\x1a\r.pm_app.Empty\"\x00\x62\x06proto3'
)




_ASSETDETAILS = _descriptor.Descriptor(
  name='AssetDetails',
  full_name='pm_app.AssetDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pm_app.AssetDetails.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=50,
)


_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='pm_app.DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pm_app.DataPoint.data', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='pm_app.DataPoint.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=89,
)


_RESULTDATAPOINT = _descriptor.Descriptor(
  name='ResultDataPoint',
  full_name='pm_app.ResultDataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=108,
)


_SUCCESS = _descriptor.Descriptor(
  name='Success',
  full_name='pm_app.Success',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='pm_app.Success.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=136,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='pm_app.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['AssetDetails'] = _ASSETDETAILS
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['ResultDataPoint'] = _RESULTDATAPOINT
DESCRIPTOR.message_types_by_name['Success'] = _SUCCESS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssetDetails = _reflection.GeneratedProtocolMessageType('AssetDetails', (_message.Message,), {
  'DESCRIPTOR' : _ASSETDETAILS,
  '__module__' : 'pm_app_pb2'
  # @@protoc_insertion_point(class_scope:pm_app.AssetDetails)
  })
_sym_db.RegisterMessage(AssetDetails)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), {
  'DESCRIPTOR' : _DATAPOINT,
  '__module__' : 'pm_app_pb2'
  # @@protoc_insertion_point(class_scope:pm_app.DataPoint)
  })
_sym_db.RegisterMessage(DataPoint)

ResultDataPoint = _reflection.GeneratedProtocolMessageType('ResultDataPoint', (_message.Message,), {
  'DESCRIPTOR' : _RESULTDATAPOINT,
  '__module__' : 'pm_app_pb2'
  # @@protoc_insertion_point(class_scope:pm_app.ResultDataPoint)
  })
_sym_db.RegisterMessage(ResultDataPoint)

Success = _reflection.GeneratedProtocolMessageType('Success', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESS,
  '__module__' : 'pm_app_pb2'
  # @@protoc_insertion_point(class_scope:pm_app.Success)
  })
_sym_db.RegisterMessage(Success)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'pm_app_pb2'
  # @@protoc_insertion_point(class_scope:pm_app.Empty)
  })
_sym_db.RegisterMessage(Empty)



_PMAPP = _descriptor.ServiceDescriptor(
  name='PMApp',
  full_name='pm_app.PMApp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=147,
  serialized_end=258,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='pm_app.PMApp.GetData',
    index=0,
    containing_service=None,
    input_type=_ASSETDETAILS,
    output_type=_DATAPOINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='pm_app.PMApp.SendData',
    index=1,
    containing_service=None,
    input_type=_DATAPOINT,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PMAPP)

DESCRIPTOR.services_by_name['PMApp'] = _PMAPP

# @@protoc_insertion_point(module_scope)
